### ISSUE TITLE
cards manipulation for Hand and Set

### ISSUE THREAD

**Issue by techwcs** [techwcs/SorryCardGame#24]
Please complete the following

Hand
addCardToHand(self, card) - adds the card to the hand ( self._hand )

removeCardFromHand(self, index) - removes the card at that position from the hand and returns it

count(self) - returns the number of cards in the hand

Set
addCardToSet(self, card) - adds the card to the set ( self._set )

removeCardFromSet(self, index) - removes the card at that position from the set and returns it

count(self) - returns the number of cards in the set

ASSIGNED TO WES

**Comment by wjh29** [comment]
finished

**Comment by techwcs** [comment]
count methods are done for both.

addCard.. and removeCard.. are about what we want for Set - just finish them for Hand

I have open questions about the remove methods, but you can finish the one for Hand for now. After our discussions, I might make a small change.

**Comment by techwcs** [comment]
Wes, please finish the methods for Hand too.

**Comment by techwcs** [comment]
DONE
