### ISSUE TITLE
Booleans for Set

### ISSUE THREAD

**Issue by techwcs** [techwcs/SorryCardGame#26]
We need a few boolean functions for Set

isComplete(self) - returns True is set is complete, False otherwise

isSafe(self) - returns True is set is safe, False otherwise

isEmpty(self) - returns True is set is empty, False otherwise

ASSIGNED TO WES

**Comment by wjh29** [comment]
finished

**Comment by wjh29** [comment]
fixed is complete

**Comment by techwcs** [comment]
Good work - thanks!
