### ISSUE TITLE
testCard

### ISSUE THREAD

**Issue by techwcs** [techwcs/SorryCardGame#27]
Please complete the Boolean function testCard for the Set class

it should return True if the card passed in can legally be added to this set.

It does NOT change the set.

ASSIGNED TO ALEX

**Comment by bsoist** [comment]
test

**Comment by techwcs** [comment]
You are on the right track.

Let's start by having you add a getValue method to the Set class.

https://github.com/techwcs/SorryCardGame/issues/28

NOTE: card is not an integer. It's an instance of Card. If you want to get the value you have to do whateverthecardnameis.getValue()

**Comment by techwcs** [comment]
Changed the name of this method to cardFits

but it works

Thanks!
